### ISSUE TITLE
OCR todo list

### ISSUE THREAD

**Issue by JunTaoLuo** [JunTaoLuo/ErukaExp#2]
- [x] Construct accuracy/recognition metrics to record what was recognized and whether values are correct @JunTaoLuo 
- [x] Construct target results
  - [x] Label Building @JunTaoLuo 
  - [x] Label Land @mihirbhaskar
- [ ] Two pass approach, first use alphabet to recognize building/total, second to recognize numbers @JunTaoLuo 
- [x] Use structure to mitigate recognizing only one of building/total/land @JunTaoLuo 
- [x] #3
- [ ] add logging + store intermediate results to class to produce summaries in ocr_alternative @mihirbhaskar 
- [ ] debug + run ocr_alternative once through @mihirbhaskar

**Comment by mihirbhaskar** [comment]
Checking for orientation and correcting it adds a few seconds to runtime for each image. May need to decide if it's worth it, especially if there are only 1/200 images that have weird orientation.

I doubt there is any systematic reason why cards would be scanned in a different way

**Comment by JunTaoLuo** [comment]
Two pass approach turned out to be slow and provided poorer results, which is surprising.
